# Shared tool configuration across platforms
tools:
  # CLI tools installed on all platforms
  common:
    - zsh
    - starship
    - atuin
    - tmux
    - eza
    - bat
    - ripgrep
    - fd
    - fzf
    - zoxide
    - jq
    - yq
    - neovim
    - git
    - gh
    - mise
    - btop
    - delta

  # macOS-only tools
  darwin:
    - broot
    - television

  # Linux-only tools  
  linux:
    - keychain
    - television

# Platform-specific paths
paths:
  darwin:
    homebrew: /opt/homebrew
    gh: /opt/homebrew/bin/gh
  linux:
    homebrew: /home/linuxbrew/.linuxbrew
    gh: /usr/bin/gh

# Editor configuration
editor: nvim

# 1Password secrets (from "API Keys" vault)
secrets:
  OPENAI_API_KEY: "op://API Keys/OPENAI_API_KEY/credential"
  OPENROUTER_API_KEY: "op://API Keys/OPENROUTER_API_KEY/credential"
  GEMINI_API_KEY: "op://API Keys/GEMINI_API_KEY/credential"
  EXA_API_KEY: "op://API Keys/EXA_API_KEY/credential"
  GROQ_API_KEY: "op://Personal/GROQ_API_KEY/credential"
  DEEPSEEK_API_KEY: "op://API Keys/DEEPSEEK_API_KEY/credential"
  TAVILY_API_KEY: "op://API Keys/TAVILY_API_KEY/credential"
