# =============================================================================
# Chezmoi Shared Data - Cross-Platform Configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Package Management
# -----------------------------------------------------------------------------
packages:
  # Core tools - installed on ALL platforms
  core:
    - zsh
    - starship
    - atuin
    - tmux
    - neovim
    - git
    - gh
    - mise

  # CLI enhancement tools - installed on ALL platforms
  cli:
    - eza
    - bat
    - ripgrep
    - fd
    - fzf
    - zoxide
    - jq
    - yq
    - delta
    - btop
    - television

  # macOS-specific tools
  darwin_only:
    - broot

  # Linux-specific tools
  linux_only:
    - keychain

  # macOS casks (GUI apps)
  darwin_casks:
    - 1password-cli
    # - ghostty  # Uncomment when available via Homebrew

  # Tools that require GUI (excluded on headless servers)
  gui_required:
    - ghostty
    - yazi

# -----------------------------------------------------------------------------
# Platform-Specific Paths
# -----------------------------------------------------------------------------
paths:
  darwin:
    homebrew: /opt/homebrew
    gh: /opt/homebrew/bin/gh
    code: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code
  linux:
    homebrew: /home/linuxbrew/.linuxbrew
    gh: /usr/bin/gh
    code: /usr/bin/code

# -----------------------------------------------------------------------------
# Editor Configuration
# -----------------------------------------------------------------------------
editor: nvim
visual: nvim

# -----------------------------------------------------------------------------
# Shell Configuration
# -----------------------------------------------------------------------------
shell:
  default: zsh
  history_size: 50000

# -----------------------------------------------------------------------------
# Theme Configuration
# -----------------------------------------------------------------------------
theme:
  name: catppuccin-mocha
  variant: mocha

# -----------------------------------------------------------------------------
# 1Password Secrets
# Using op:// secret reference syntax
# See: https://developer.1password.com/docs/cli/secret-reference-syntax
# -----------------------------------------------------------------------------
secrets:
  OPENAI_API_KEY: "op://Development/OPENAI_API_KEY/api key"
  OPENROUTER_API_KEY: "op://Development/OPENROUTER_API_KEY/token"
  GEMINI_API_KEY: "op://Development/GEMINI_API_KEY/password"
  EXA_API_KEY: "op://Development/EXA_API_KEY/password"
  GROQ_API_KEY: "op://Development/GROQ_API_KEY/credential"
  DEEPSEEK_API_KEY: "op://Development/DEEPSEEK_API_KEY/password"
  TAVILY_API_KEY: "op://Development/TAVILY_API_KEY/password"

# -----------------------------------------------------------------------------
# Machine-Specific Feature Flags
# These can be overridden in .chezmoi.toml.tmpl per machine
# -----------------------------------------------------------------------------
features:
  # Enable 1Password CLI integration
  onepassword: true
  # Enable AI coding assistants
  ai_assistants: true
  # Enable development containers
  devcontainers: false
