# Shared tool configuration across platforms
tools:
  # CLI tools installed on all platforms
  common:
    - zsh
    - starship
    - atuin
    - tmux
    - eza
    - bat
    - ripgrep
    - fd
    - fzf
    - zoxide
    - jq
    - yq
    - neovim
    - git
    - gh
    - mise
    - btop
    - delta

  # macOS-only tools
  darwin:
    - broot
    - television

  # Linux-only tools  
  linux:
    - keychain
    - television

# Platform-specific paths
paths:
  darwin:
    homebrew: /opt/homebrew
    gh: /opt/homebrew/bin/gh
  linux:
    homebrew: /home/linuxbrew/.linuxbrew
    gh: /usr/bin/gh

# Editor configuration
editor: nvim

# 1Password secrets (using correct field names per item)
secrets:
  OPENAI_API_KEY: "op://Development/OPENAI_API_KEY/api key"
  OPENROUTER_API_KEY: "op://Development/OPENROUTER_API_KEY/token"
  GEMINI_API_KEY: "op://Development/GEMINI_API_KEY/password"
  EXA_API_KEY: "op://Development/EXA_API_KEY/password"
  GROQ_API_KEY: "op://Development/GROQ_API_KEY/credential"
  DEEPSEEK_API_KEY: "op://Development/DEEPSEEK_API_KEY/password"
  TAVILY_API_KEY: "op://Development/TAVILY_API_KEY/password"
